name: face_match_liveness
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/models/mobilefacenet.tflite
