name: face_match_liveness
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/widiramadhan/face_match_liveness
issue_tracker: https://github.com/widiramadhan/face_match_liveness/issues

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.24.0

flutter:
  assets:
    - assets/models/mobilefacenet.tflite
